[package]
name = "advent_of_code_rust"
version = "0.1.0"
authors = ["Dima Enns <dieter.enns@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]